import type { UiLanguage } from "./language.ts";
export { isUiLanguage, resolveLanguageSelection, SUPPORTED_UI_LANGUAGES, type LanguageSelection, type UiLanguage } from "./language.ts";

const en = {
  loading: "Loading",
  chat: "Chat",
  workflows: "Workflows",
  newChat: "New Chat",
  history: "History",
  noHistory: "No history yet",
  signedIn: "Signed in",
  settings: "Settings",
  language: "Language",
  auto: "Auto-detect",
  english: "English",
  vietnamese: "Vietnamese",
  rename: "Rename",
  delete: "Delete",
  close: "Close",
  citations: "Citations",
  researchPrompt: "What should we research?",
  researchIntro: "Ask a finance research question. V1 returns deterministic mock responses with trusted local visual artifacts.",
  promptVcbChange: "What changed for VCB today?",
  promptGoldPressure: "Explain gold price pressure this week.",
  promptSectorMomentum: "Compare banking and retail momentum.",
  promptClosingRisks: "What risks should I watch before market close?",
  askPlaceholder: "Ask FinMind...",
  message: "Message",
  send: "Send message",
  done: "Done",
  waiting: "Waiting for answer...",
  download: "Download",
  openFile: "Open file",
  market: "Market",
  symbol: "Symbol",
  run: "Run",
  noWorkflows: "No workflows available.",
  workflowLoadFailed: "Failed to load workflows",
  markets: "Markets",
  inputs: "Inputs",
  stages: "Stages",
  sections: "Sections",
  evidence: "Evidence",
  citationsRequired: "Citations required",
  citationsOptional: "Citations optional",
  noChart: "No chart",
  researchOutput: "Research output",
  sectionCollectedData: "Collected Data",
  sectionFundamentalAnalysis: "Fundamental Analysis",
  sectionTechnicalAnalysis: "Technical Analysis",
  unsupportedMarket: "Unsupported market",
  marketVnStocks: "VN stocks",
  marketGold: "Gold",
  inputMarket: "market",
  inputSymbol: "symbol",
  stageCollectData: "collect data",
  stageDataAudit: "data audit",
  stageTechnicalAnalysis: "technical analysis",
  stageFundamentalAnalysis: "fundamental analysis",
  priceTrend: "Price trend",
  goldPriceTrend: "XAUUSD daily price trend",
  workflowCollectorTitle: "VN Financial Data Collector",
  workflowCollectorDescription: "Collects and checks VN stock financial data before analysis.",
  workflowFundamentalTitle: "VN Fundamental Analysis",
  workflowFundamentalDescription: "Analyzes financial health, earnings quality, and growth trends.",
  workflowTechnicalTitle: "VN Technical Analysis",
  workflowTechnicalDescription: "Analyzes verified price data and technical indicators.",
  promptCollector: "Collect and audit financial data for stock {symbol}",
  promptFundamental: "Analyze the fundamentals of stock {symbol}",
  promptTechnical: "Analyze the technicals of stock {symbol}",
  promptGenericStock: "Analyze stock {symbol}",
  loginTagline: "Personalized finance research assistant.",
  signInContext: "Sign in to access our product.",
  username: "Username",
  emailPlaceholder: "Enter your email",
  password: "Password",
  passwordPlaceholder: "Enter your password",
  continue: "Continue",
  signingIn: "Signing in…",
  loginFailed: "Login failed",
  protectedAccess: "Protected access. Authorized internal accounts only.",
  showPassword: "Show password",
  hidePassword: "Hide password",
  lineChart: "Line chart",
  candleChart: "Candlestick chart",
  chartControls: "Chart controls",
  chartUnavailable: "Chart unavailable",
  missingData: "missing data",
  missingPriceSeries: "price-series data is unavailable",
  unsupportedChartRequirement: "this chart type is unavailable",
  artifactDetail: "Artifact detail",
  chart: "Chart",
  chartArtifact: "Chart artifact",
  spreadsheet: "Spreadsheet",
  file: "File",
  collapsePanel: "Collapse right panel",
  openSettings: "Open settings",
  closeSettings: "Close settings",
  closeWorkflowDetails: "Close workflow details",
  closeCitation: "Close citation",
  expandLeftPanel: "Expand left panel",
  collapseLeftPanel: "Collapse left panel",
  renameConversation: "Rename conversation",
  conversationActions: "Conversation actions",
  logoutRole: "Log out {role}",
  deleteConversationConfirm: "Delete this conversation?\n\n{title}",
  working: "Working",
  completedSteps: "Completed {count} steps",
  workflowFailed: "Workflow failed",
  primaryNav: "Primary navigation",
  primarySurfaces: "Primary surfaces",
  stepCollectMarketData: "Collect market data",
  stepCollectVnStockData: "Collect VN stock data",
  stepAuditCoverage: "Audit source coverage",
  stepTechnicalAnalysis: "Analyze technical momentum",
  stepFundamentalAnalysis: "Analyze fundamentals",
  stepNewsReview: "Review news signals",
  stepRiskReview: "Review downside risks",
  mockResponse: "Mock response for {subject}. This is a deterministic V1 chat answer; it does not call the production orchestrator.",
  mockResearchView: "Here is a mock research view for {subject}. Inline visuals are rendered from trusted local templates only.",
  quickView: "{subject} quick view",
  direction: "Direction",
  mixed: "Mixed",
  constructive: "Constructive",
  freshness: "Freshness",
  mockEvidence: "Mock citations",
  mockReport: "{subject} mock report",
  mockReportSummary: "Open the full deterministic report in the right-side panel."
} as const;

export type MessageKey = keyof typeof en;

const vi: Record<MessageKey, string> = {
  loading: "Đang tải",
  chat: "Trò chuyện",
  workflows: "Quy trình",
  newChat: "Trò chuyện mới",
  history: "Lịch sử",
  noHistory: "Chưa có lịch sử",
  signedIn: "Đã đăng nhập",
  settings: "Cài đặt",
  language: "Ngôn ngữ",
  auto: "Tự động nhận diện",
  english: "English",
  vietnamese: "Tiếng Việt",
  rename: "Đổi tên",
  delete: "Xóa",
  close: "Đóng",
  citations: "Trích dẫn",
  researchPrompt: "Bạn muốn nghiên cứu điều gì?",
  researchIntro: "Đặt câu hỏi nghiên cứu tài chính. V1 trả về phản hồi mô phỏng xác định cùng bằng chứng trực quan cục bộ.",
  promptVcbChange: "Hôm nay VCB có gì thay đổi?",
  promptGoldPressure: "Giải thích áp lực giá vàng tuần này.",
  promptSectorMomentum: "So sánh động lượng ngành ngân hàng và bán lẻ.",
  promptClosingRisks: "Tôi nên theo dõi rủi ro nào trước khi thị trường đóng cửa?",
  askPlaceholder: "Hỏi FinMind...",
  message: "Tin nhắn",
  send: "Gửi tin nhắn",
  done: "Hoàn tất",
  waiting: "Đang chờ câu trả lời...",
  download: "Tải xuống",
  openFile: "Mở tệp",
  market: "Thị trường",
  symbol: "Mã",
  run: "Chạy",
  noWorkflows: "Không có quy trình khả dụng.",
  workflowLoadFailed: "Không thể tải danh sách quy trình",
  markets: "Thị trường",
  inputs: "Đầu vào",
  stages: "Các bước",
  sections: "Nội dung",
  evidence: "Bằng chứng",
  citationsRequired: "Yêu cầu trích dẫn",
  citationsOptional: "Trích dẫn tùy chọn",
  noChart: "Không có biểu đồ",
  researchOutput: "Kết quả nghiên cứu",
  sectionCollectedData: "Dữ liệu đã thu thập",
  sectionFundamentalAnalysis: "Phân tích cơ bản",
  sectionTechnicalAnalysis: "Phân tích kỹ thuật",
  unsupportedMarket: "Thị trường không được hỗ trợ",
  marketVnStocks: "Cổ phiếu VN",
  marketGold: "Vàng",
  inputMarket: "thị trường",
  inputSymbol: "mã",
  stageCollectData: "thu thập dữ liệu",
  stageDataAudit: "kiểm tra dữ liệu",
  stageTechnicalAnalysis: "phân tích kỹ thuật",
  stageFundamentalAnalysis: "phân tích cơ bản",
  priceTrend: "Xu hướng giá",
  goldPriceTrend: "Xu hướng giá XAUUSD theo ngày",
  workflowCollectorTitle: "Thu thập dữ liệu tài chính VN",
  workflowCollectorDescription: "Thu thập và kiểm tra dữ liệu tài chính cổ phiếu VN trước khi phân tích.",
  workflowFundamentalTitle: "Phân tích cơ bản VN",
  workflowFundamentalDescription: "Phân tích sức khỏe tài chính, chất lượng lợi nhuận và xu hướng tăng trưởng.",
  workflowTechnicalTitle: "Phân tích kỹ thuật VN",
  workflowTechnicalDescription: "Phân tích dữ liệu giá và chỉ báo kỹ thuật đã được kiểm chứng.",
  promptCollector: "Thu thập và kiểm tra dữ liệu tài chính cho mã {symbol}",
  promptFundamental: "Phân tích cơ bản mã {symbol}",
  promptTechnical: "Phân tích kỹ thuật mã {symbol}",
  promptGenericStock: "Phân tích mã {symbol}",
  loginTagline: "Trợ lý nghiên cứu tài chính dành riêng cho bạn.",
  signInContext: "Đăng nhập để sử dụng sản phẩm.",
  username: "Tên đăng nhập",
  emailPlaceholder: "Nhập email",
  password: "Mật khẩu",
  passwordPlaceholder: "Nhập mật khẩu",
  continue: "Tiếp tục",
  signingIn: "Đang đăng nhập…",
  loginFailed: "Đăng nhập thất bại",
  protectedAccess: "Truy cập được bảo vệ. Chỉ dành cho tài khoản nội bộ được cấp quyền.",
  showPassword: "Hiện mật khẩu",
  hidePassword: "Ẩn mật khẩu",
  lineChart: "Biểu đồ đường",
  candleChart: "Biểu đồ nến",
  chartControls: "Điều khiển biểu đồ",
  chartUnavailable: "Biểu đồ không khả dụng",
  missingData: "thiếu dữ liệu",
  missingPriceSeries: "không có dữ liệu chuỗi giá",
  unsupportedChartRequirement: "loại biểu đồ này không khả dụng",
  artifactDetail: "Chi tiết bằng chứng",
  chart: "Biểu đồ",
  chartArtifact: "Dữ liệu biểu đồ",
  spreadsheet: "Bảng tính",
  file: "Tệp",
  collapsePanel: "Thu gọn bảng bên phải",
  openSettings: "Mở cài đặt",
  closeSettings: "Đóng cài đặt",
  closeWorkflowDetails: "Đóng chi tiết quy trình",
  closeCitation: "Đóng trích dẫn",
  expandLeftPanel: "Mở rộng bảng bên trái",
  collapseLeftPanel: "Thu gọn bảng bên trái",
  renameConversation: "Đổi tên cuộc trò chuyện",
  conversationActions: "Thao tác cuộc trò chuyện",
  logoutRole: "Đăng xuất {role}",
  deleteConversationConfirm: "Xóa cuộc trò chuyện này?\n\n{title}",
  working: "Đang xử lý",
  completedSteps: "Đã hoàn tất {count} bước",
  workflowFailed: "Quy trình thất bại",
  primaryNav: "Điều hướng chính",
  primarySurfaces: "Khu vực chính",
  stepCollectMarketData: "Thu thập dữ liệu thị trường",
  stepCollectVnStockData: "Thu thập dữ liệu cổ phiếu VN",
  stepAuditCoverage: "Kiểm tra độ bao phủ nguồn",
  stepTechnicalAnalysis: "Phân tích động lượng kỹ thuật",
  stepFundamentalAnalysis: "Phân tích cơ bản",
  stepNewsReview: "Xem xét tín hiệu tin tức",
  stepRiskReview: "Xem xét rủi ro giảm giá",
  mockResponse: "Phản hồi mô phỏng cho {subject}. Đây là câu trả lời V1 xác định và không gọi bộ điều phối production.",
  mockResearchView: "Đây là góc nhìn nghiên cứu mô phỏng cho {subject}. Nội dung trực quan chỉ được kết xuất từ mẫu cục bộ đáng tin cậy.",
  quickView: "Tổng quan nhanh {subject}",
  direction: "Xu hướng",
  mixed: "Trái chiều",
  constructive: "Tích cực",
  freshness: "Thời điểm",
  mockEvidence: "Trích dẫn mô phỏng",
  mockReport: "Báo cáo mô phỏng {subject}",
  mockReportSummary: "Mở báo cáo xác định đầy đủ trong bảng bên phải."
};

const messages: Record<UiLanguage, Record<MessageKey, string>> = { en, vi };
type MessageParams = Record<string, string | number>;

function interpolate(template: string, params: MessageParams): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : match
  );
}

export function translate(language: UiLanguage, key: MessageKey, params: MessageParams = {}): string {
  const template = messages[language]?.[key] ?? messages.en[key];
  return interpolate(template, params);
}

export function workflowStepTitle(
  language: UiLanguage,
  stepId: string,
  market?: string
): string {
  if (stepId === "collect_data") {
    return translate(
      language,
      market?.trim().toUpperCase() === "VN_STOCK"
        ? "stepCollectVnStockData"
        : "stepCollectMarketData"
    );
  }
  if (stepId.includes("data-auditor")) return translate(language, "stepAuditCoverage");
  if (stepId.includes("technical-analysis")) return translate(language, "stepTechnicalAnalysis");
  if (stepId.includes("fundamental-analysis")) return translate(language, "stepFundamentalAnalysis");
  if (stepId.includes("news")) return translate(language, "stepNewsReview");
  if (stepId.includes("risk")) return translate(language, "stepRiskReview");
  return stepId
    .replace(/^vn-/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}
